### ISSUE TITLE
ping is Not working 

### ISSUE THREAD

**Issue by rsoorajs** [zyrouge/web-status-monitor#2]
i tried to add my second website like this.but not working.can you show me the sample

```
urls: https://buddytraveler.com
  - path: "https://google.com"
    type: "get"
urls: 
  - path: "https://buddytraveler.com"
    type: "get" 
```
